
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Bartu
 */
public class StokUygulaması extends javax.swing.JFrame {

    /**
     * Creates new form StokUygulaması
     */
    public StokUygulaması() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cb_kategori = new javax.swing.JComboBox<>();
        ürün_adi = new javax.swing.JTextField();
        tf_fiyat = new javax.swing.JTextField();
        mesaj_yazisi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ürün_table = new javax.swing.JTable();
        ürün_ekle = new javax.swing.JButton();
        ürün_güncelleme = new javax.swing.JButton();
        ürün_sil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ürün Adı : ");

        jLabel2.setText("Kategori : ");

        jLabel3.setText("Fiyat : ");

        cb_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kültür Sanat", "Yemek", "Elektronik" }));

        tf_fiyat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_fiyatActionPerformed(evt);
            }
        });

        mesaj_yazisi.setForeground(new java.awt.Color(255, 0, 102));

        ürün_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ürün İsmi", "Kategori", "Fiyat"
            }
        ));
        ürün_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ürün_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ürün_table);

        ürün_ekle.setText("Ürün Ekle");
        ürün_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ürün_ekleActionPerformed(evt);
            }
        });

        ürün_güncelleme.setText("Ürün Güncelle");
        ürün_güncelleme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ürün_güncellemeActionPerformed(evt);
            }
        });

        ürün_sil.setText("Ürün Sil");
        ürün_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ürün_silActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_fiyat)
                            .addComponent(ürün_adi)
                            .addComponent(cb_kategori, 0, 201, Short.MAX_VALUE))
                        .addGap(224, 224, 224)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ürün_ekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ürün_güncelleme, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(ürün_sil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ürün_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ürün_ekle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ürün_sil))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(ürün_güncelleme)))
                .addGap(73, 73, 73)
                .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_fiyatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_fiyatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_fiyatActionPerformed

    private void ürün_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ürün_ekleActionPerformed
            mesaj_yazisi.setText(" ");
            DefaultTableModel model=(DefaultTableModel)ürün_table.getModel();
            
            if(ürün_adi.getText().trim().equals("")){ // bu trim metoduyla başındaki ve sonundaki boşlukları silmil oluyoruz
                mesaj_yazisi.setText("Ürün ismi boş bırakılamaz!");
            }
            else {
                Object[] eklenecek = {ürün_adi.getText(),cb_kategori.getSelectedItem().toString(),tf_fiyat.getText()};
                model.addRow(eklenecek);
            }   
        
        
        
    }//GEN-LAST:event_ürün_ekleActionPerformed

    private void ürün_güncellemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ürün_güncellemeActionPerformed
        
        mesaj_yazisi.setText("");
        
        DefaultTableModel model =(DefaultTableModel)ürün_table.getModel();
        
        int secili_row = ürün_table.getSelectedRow();
        
        if(secili_row == -1 ){
            
            if(ürün_table.getRowCount()== 0){
                
                mesaj_yazisi.setText("Ürün tablosu şuanda boş!");
                
            }
            else {
                mesaj_yazisi.setText("Lütfen güncellenecek bir ürün seçiniz...");
            }
        }
        else{
            model.setValueAt(ürün_adi.getText(), secili_row, 0);
            model.setValueAt(cb_kategori.getSelectedItem().toString(), secili_row, 1);
            model.setValueAt(tf_fiyat.getText(), secili_row, 2);
             
            mesaj_yazisi.setText("Ürün başarılı bir şekilde güncellendi!");
    }
        
        
    }//GEN-LAST:event_ürün_güncellemeActionPerformed

    private void ürün_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ürün_tableMouseClicked
        // ürüne basınca ürün arama yerine yerleşiyor
        DefaultTableModel model=(DefaultTableModel)ürün_table.getModel();
        int secili_row = ürün_table.getSelectedRow();
        
        ürün_adi.setText(model.getValueAt(secili_row, 0).toString());
        cb_kategori.setSelectedItem(model.getValueAt(secili_row, 1));
        tf_fiyat.setText(model.getValueAt(secili_row, 2).toString());
    }//GEN-LAST:event_ürün_tableMouseClicked

    private void ürün_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ürün_silActionPerformed
        DefaultTableModel model=(DefaultTableModel)ürün_table.getModel();
        int secili_row = ürün_table.getSelectedRow();
        
        if(secili_row == -1) {
            if(ürün_table.getRowCount() == 0 ) {
                
                mesaj_yazisi.setText("Ürün tablonuz şuanda boş!");
                
            }
            else { 
                mesaj_yazisi.setText("Lütfen silinecek bir ürün seçiniz...");
            }
        }
        else {
            model.removeRow(secili_row);
            mesaj_yazisi.setText("Ürün başarıyla silindi.");
        }
    }//GEN-LAST:event_ürün_silActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StokUygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StokUygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StokUygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StokUygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StokUygulaması().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_kategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JTextField tf_fiyat;
    private javax.swing.JTextField ürün_adi;
    private javax.swing.JButton ürün_ekle;
    private javax.swing.JButton ürün_güncelleme;
    private javax.swing.JButton ürün_sil;
    private javax.swing.JTable ürün_table;
    // End of variables declaration//GEN-END:variables
}
